#!/usr/bin/env bash
# configure web-02 to be identical to web-01
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on
#!/usr/bin/env bash

# Update package repositories
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx



# Create index and 404 pages
echo 'Hello World!' | sudo tee /var/www/html/index.html

#performing redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/kingbascee permanent;"

sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#creating a custom error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Custom HTTP RESPONSE HEADER

sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#Test for syntax Error
sudo nginx -t

# Restart Nginx service
sudo service nginx restart
